dist: bionic
language: python

jobs:
  fast_finish: true
  include:
    - python: '2.7'
      env: TOX_ENV=py27
    - python: '3.8'
      env: TOX_ENV=py3
    - python: nightly
      env: TOX_ENV=py3
    - python: '3.8'
      env: TOX_ENV=pep8

install:
    - travis_retry pip install tox tox-venv
    - python -VV

script:
    - "tox -e $TOX_ENV -- $TOX_ARGS"
